[workspace]
resolver = "2"
members = [
    "crackers",
    "llvm",

    "cli",
]

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false
codegen-units = 1
panic = "abort"
overflow-checks = false
